name: Generate Release Notes

on:
  push:
    tags:
      - '*'

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Release Notes
        uses: mikeal/release-notes-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: "Release ${{ github.ref }}"
          body: ${{ steps.release-notes.outputs.notes }}
